# Generated by Django 4.0.1 on 2022-03-05 16:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=200)),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('ending_date', models.DateField(verbose_name='ending date')),
                ('event_text', models.TextField(max_length=80000)),
                ('event_main_text_culling', models.IntegerField(default=800, validators=[django.core.validators.MaxValueValidator(800), django.core.validators.MinValueValidator(1)])),
                ('tags', models.ManyToManyField(to='EventCalendar.EventTag')),
            ],
        ),
        migrations.CreateModel(
            name='EventComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=600)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventCalendar.eventpage')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
