# Generated by Django 4.0.1 on 2022-03-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventCalendar', '0005_eventpage_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='event_prize',
            field=models.CharField(max_length=200),
        ),
    ]
