# Generated by Django 4.0.1 on 2022-03-15 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EventCalendar', '0006_alter_eventpage_event_prize'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcomment',
            name='pub_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
