# Generated by Django 4.0.1 on 2022-05-07 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventCalendar', '0009_alter_eventpage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcomment',
            options={'ordering': ['pub_datetime']},
        ),
        migrations.RenameField(
            model_name='eventcomment',
            old_name='pub_time',
            new_name='pub_datetime',
        ),
    ]
