# Generated by Django 4.0.1 on 2022-05-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventCalendar', '0011_eventpage_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='ending_date',
            field=models.DateTimeField(verbose_name='ending date'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='start_date',
            field=models.DateTimeField(verbose_name='start date'),
        ),
    ]
