# Generated by Django 4.0.1 on 2022-06-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventCalendar', '0013_remove_eventpage_event_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='event_image',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='link to the picture used in the post'),
        ),
    ]
