# Generated by Django 4.0.1 on 2022-05-04 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsFeed', '0002_comment_pub_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'permissions': [('create_new_news', 'Can create new news'), ('delete_their_news', 'Can delete their own news'), ('delete_any_news', 'Can delete any news')]},
        ),
    ]
