# Generated by Django 4.0.1 on 2022-06-05 09:50

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsFeed', '0009_newsarticle_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='news_text',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
