# Generated by Django 4.0.1 on 2022-06-05 14:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NewsFeed', '0010_alter_newsarticle_news_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 5, 14, 39, 29, 239384, tzinfo=utc), verbose_name='date published'),
        ),
    ]
