# Generated by Django 4.2.2 on 2023-07-03 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsFeed', '0013_alter_newsarticle_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 3, 14, 13, 18, 532115, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
