# Generated by Django 4.2.2 on 2023-07-03 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsFeed', '0018_alter_newsarticle_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 3, 15, 0, 25, 997348, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
