# Generated by Django 4.0.1 on 2022-05-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_directionslist_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='direction_info',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='event_type_info',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_info',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
