# Generated by Django 4.0.1 on 2022-05-07 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_project_direction_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('can_manage_projects', 'Can manage projects'), ('can_moderate_projects', 'Can moderate projects')]},
        ),
    ]
