# Generated by Django 4.0.1 on 2022-05-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_project_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(blank=True, choices=[('pen', 'Pending'), ('acc', 'Accepted'), ('den', 'Denied'), ('act', 'Active'), ('fin', 'Finished')], default='p', help_text='Current project status', max_length=3),
        ),
    ]
