# Generated by Django 4.0.1 on 2022-05-16 08:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_project_project_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 8, 30, 26, 642402, tzinfo=utc), verbose_name='Date Time published'),
        ),
    ]
