# Generated by Django 4.0.1 on 2022-05-17 10:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_project_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('can_manage_projects', 'Can manage projects'), ('can_moderate_projects', 'Can moderate incoming projects'), ('can_create_projects', 'Can create projects')]},
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 10, 38, 43, 555899, tzinfo=utc), verbose_name='Date Time published'),
        ),
        migrations.AlterField(
            model_name='projectentry',
            name='status',
            field=models.CharField(blank=True, choices=[('pen', 'Pending'), ('acc', 'Accepted'), ('den', 'Denied')], default='pen', help_text='Current entry status', max_length=3),
        ),
    ]
