# Generated by Django 4.0.1 on 2022-05-20 07:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_project_project_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 20, 7, 47, 42, 290090, tzinfo=utc), verbose_name='Date Time published'),
        ),
        migrations.AlterField(
            model_name='projectentry',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 20, 7, 47, 42, 293091, tzinfo=utc), verbose_name='Время, когда заяка была отправлена'),
        ),
        migrations.AlterField(
            model_name='projectentry',
            name='status_changed_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 20, 7, 47, 42, 293091, tzinfo=utc), verbose_name='Время, когда статус заявки был изменен'),
        ),
        migrations.CreateModel(
            name='ProjectNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_text', models.CharField(max_length=800)),
                ('pub_time', models.DateTimeField(default=datetime.datetime(2022, 5, 20, 7, 47, 42, 295091, tzinfo=utc))),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
        ),
    ]
