# Generated by Django 4.0.1 on 2022-05-21 06:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_projectnotice_pub_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectchatmessage',
            old_name='pub_time',
            new_name='pub_datetime',
        ),
        migrations.RenameField(
            model_name='teamchatmessage',
            old_name='pub_time',
            new_name='pub_datetime',
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 6, 59, 55, 681325, tzinfo=utc), verbose_name='Date Time published'),
        ),
        migrations.AlterField(
            model_name='projectentry',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 6, 59, 55, 684326, tzinfo=utc), verbose_name='Время, когда заяка была отправлена'),
        ),
        migrations.AlterField(
            model_name='projectentry',
            name='status_changed_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 6, 59, 55, 684326, tzinfo=utc), verbose_name='Время, когда статус заявки был изменен'),
        ),
        migrations.AlterField(
            model_name='projectnotice',
            name='pub_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 6, 59, 55, 685327, tzinfo=utc)),
        ),
    ]
