# Generated by Django 4.0.1 on 2022-05-21 07:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_pub_time_projectchatmessage_pub_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_looking_for_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='team_info',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='team_lfg_message',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 7, 10, 9, 591871, tzinfo=utc), verbose_name='Date Time published'),
        ),
        migrations.AlterField(
            model_name='projectentry',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 7, 10, 9, 593871, tzinfo=utc), verbose_name='Время, когда заяка была отправлена'),
        ),
        migrations.AlterField(
            model_name='projectentry',
            name='status_changed_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 7, 10, 9, 593871, tzinfo=utc), verbose_name='Время, когда статус заявки был изменен'),
        ),
        migrations.AlterField(
            model_name='projectnotice',
            name='pub_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 7, 10, 9, 595872, tzinfo=utc)),
        ),
    ]
