# Generated by Django 4.0.1 on 2022-05-21 07:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_team_is_looking_for_group_team_team_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='maximum_members_in_team',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 7, 11, 53, 289965, tzinfo=utc), verbose_name='Date Time published'),
        ),
        migrations.AlterField(
            model_name='projectentry',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 7, 11, 53, 292965, tzinfo=utc), verbose_name='Время, когда заяка была отправлена'),
        ),
        migrations.AlterField(
            model_name='projectentry',
            name='status_changed_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 7, 11, 53, 292965, tzinfo=utc), verbose_name='Время, когда статус заявки был изменен'),
        ),
        migrations.AlterField(
            model_name='projectnotice',
            name='pub_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 7, 11, 53, 293965, tzinfo=utc)),
        ),
    ]
