# Generated by Django 4.0.1 on 2022-06-05 09:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_project_maximum_members_in_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 5, 9, 50, 0, 804500, tzinfo=utc), verbose_name='Date Time published'),
        ),
        migrations.AlterField(
            model_name='projectentry',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 5, 9, 50, 0, 806501, tzinfo=utc), verbose_name='Время, когда заяка была отправлена'),
        ),
        migrations.AlterField(
            model_name='projectentry',
            name='status_changed_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 5, 9, 50, 0, 806501, tzinfo=utc), verbose_name='Время, когда статус заявки был изменен'),
        ),
        migrations.AlterField(
            model_name='projectnotice',
            name='pub_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 5, 9, 50, 0, 808501, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teamentry',
            name='status',
            field=models.CharField(blank=True, choices=[('pen', 'Рассматривается'), ('acc', 'Принято'), ('den', 'Отклонено')], default='pen', help_text='Current entry status', max_length=3),
        ),
    ]
